import type { Metadata } from 'next'
import Link from 'next/link'
import { Button } from '@/components/Button'
import { Icon } from '@/components/Icon'
import { SectionIntro } from '@/components/SectionIntro'
import { faqs, meta, services } from '@/data/site'
export const metadata: Metadata = { ...meta.home, openGraph: { title: meta.home.title, description: meta.home.description, url: '/' } }
const problems=[['01','Bank and enterprise requirements','Your prospective clients may request evidence of privacy governance, security controls and accountable ownership.'],['02','Unclear data responsibilities','Controller, processor, vendor and overseas-access responsibilities may not be properly documented.'],['03','Privacy risks inside products','Data collection, access, retention, profiling and third-party integrations can introduce unmanaged risks.'],['04','Fragile IT operations','Weak backups, uncontrolled access and inconsistent monitoring can interrupt business and undermine customer trust.']]
const steps=[['01','Discover','Understand the organisation, products, systems, vendors and business requirements.'],['02','Assess','Map risks, responsibilities, controls and missing evidence.'],['03','Prioritise','Create a practical action plan based on business impact and urgency.'],['04','Monitor','Track progress, provide advice and report unresolved risks to management.']]
const sectors=['Fintech and lending technology','SaaS and technology platforms','Foreign companies entering Indonesia','Clinics and healthcare operators','Professional services','Distributors and multi-site businesses']
const why=['Indonesian operating context','Privacy and technology expertise','Clear scope and deliverables','Management-level reporting','Practical remediation roadmap','One accountable commercial partner']
export default function Home(){return <main id="main"><section className="hero"><div className="hero-copy"><span className="eyebrow">Privacy · Security · Resilience</span><h1>Privacy governance and resilient IT operations for businesses in Indonesia</h1><p className="hero-lead">Navigate Indonesia’s personal-data requirements, strengthen operational controls and maintain dependable technology services with one accountable local partner.</p><div className="hero-actions"><Button href="/contact">Schedule a Discovery Call</Button><Button href="#services" secondary>Explore Our Services</Button></div></div><div className="hero-visual"><span className="signal"/><div className="visual-title"><small>OPERATING CONTEXT · INDONESIA</small><h2>Governance connected to real operations.</h2></div><div className="visual-metrics"><span><b>Privacy</b>Accountable oversight</span><span><b>Security</b>Practical controls</span><span><b>IT operations</b>Dependable delivery</span></div></div></section>
<section className="trust-strip"><div className="shell trust-grid"><div><span>●</span>Indonesia-focused delivery</div><div><span>●</span>Product and technology experience</div><div><span>●</span>Documented governance and reporting</div></div></section>
<section className="section shell"><SectionIntro eyebrow="Commercial context" title="Governance gaps become commercial risks" text="Clear ownership and operating evidence help businesses respond to customer due diligence and manage risk with confidence."/><div className="card-grid">{problems.map(x=><article className="card" key={x[0]}><span className="card-number">{x[0]}</span><h3 style={{marginTop:60}}>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="section shell" id="services"><SectionIntro eyebrow="Our services" title="Practical governance and operational support" text="Choose a focused engagement or combine services around your operating priorities."/><div className="card-grid">{services.map(s=><article className="card" key={s.href}><div className="card-icon"><Icon name={s.icon}/></div><h3>{s.title}</h3><p>{s.description}</p><Link className="card-link" href={s.href}>Explore {s.title} →</Link></article>)}</div></section>
<section className="dark-section"><div className="section shell"><SectionIntro light eyebrow="How PatuhData works" title="Structured from discovery through monitoring" text="A consistent delivery model makes responsibilities, risks and next actions visible."/><div className="process-grid">{steps.map(x=><article className="process-step" key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section className="section shell"><SectionIntro eyebrow="Industry focus" title="Built for data-intensive and operationally dependent businesses"/><div className="tag-grid">{sectors.map(x=><span className="tag" key={x}>{x}</span>)}</div></section>
<section className="section shell"><SectionIntro eyebrow="Why PatuhData" title="Practical advice with accountable delivery" text="We connect management expectations with the work required across products, vendors and technology operations."/><div className="why-grid">{why.map((x,i)=><article className="why-item" key={x}><h3>{String(i+1).padStart(2,'0')} · {x}</h3><p>Defined responsibilities, documented outputs and priorities aligned to business impact.</p></article>)}</div></section>
<section className="section shell"><SectionIntro eyebrow="Frequently asked questions" title="Clear answers about scope and accountability"/><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
<section className="cta-band shell"><div><span className="eyebrow" style={{color:'#9fc0ff'}}>Start with discovery</span><h2>Start with a focused discovery session</h2></div><div><p>Tell us about your product, Indonesian operation or technology environment. We will help define the appropriate service scope, responsibilities and next steps.</p><div className="hero-actions"><Button href="/contact">Schedule a Discovery Call</Button><Button href="/contact" secondary>Contact PatuhData</Button></div></div></section></main>}
