import { architectCTA, coreSolutions, CoreSolution, deliverySteps, differentiators, industries, indonesiaInterest, inquiryHref, positioning } from '../data/coreSolutions'
import { resourceArticles } from '../data/resourceArticles'

const technologyLogos = [
  { name: 'Veeam', src: '/Veeam_logo.png' },
  { name: 'Synology', src: '/Synology--Streamline-Simple-Icons.svg' },
  { name: 'AWS', src: '/Amazon_Web_Services_Logo.svg' },
  { name: 'Google Cloud', src: '/Google-Cloud-Logo.png' },
  { name: 'VMware', src: '/VMware-Logo.png' },
  { name: 'Sophos', src: '/Sophos_logo.png' },
  { name: 'MikroTik', src: '/MikroTik_Logo_(2022).svg' },
  { name: 'Wazuh', src: '/wazuh.png' },
  { name: 'Keycloak', src: '/Logo_of_Keycloak.svg' },
]

function Arrow() { return <span aria-hidden="true">↗</span> }
export function ArchitectLink({ interest, label = architectCTA }: { interest?: string; label?: string }) {
  return <a className="pd-button" href={interest ? inquiryHref(interest) : '/contact'}>{label}<Arrow /></a>
}
export function FinalCTA() {
  return <section className="pd-final"><div><span className="pd-eyebrow">LET’S START WITH THE RIGHT QUESTIONS</span><h2>Not sure where your biggest technology risk is?</h2><p>Talk with PatuhData about your current environment, business requirements, and priorities.</p></div><ArchitectLink /></section>
}
export function DeliveryProcess() {
  return <section className="pd-section pd-process" id="approach"><div className="pd-heading"><span className="pd-eyebrow">OUR APPROACH</span><h2>One partner from risk to implementation.</h2><p>We diagnose and design first. Technology follows the business requirement.</p></div><ol className="pd-steps">{deliverySteps.map(([title, text], index) => <li key={title}><span className="pd-step-number">0{index + 1}</span><h3>{title}</h3><p>{text}</p>{index < 4 && <span className="pd-step-arrow" aria-hidden="true">→</span>}</li>)}</ol></section>
}
export function ResourceCards() {
  return <div className="pd-resources">{resourceArticles.map(article => <a className="pd-resource" href={`/resources/${article.slug}`} key={article.slug}><span className="pd-eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.summary}</p><span className="pd-card-link">Read the guide <Arrow /></span></a>)}</div>
}
export default function CoreWebsite() {
  return <main id="top" className="pd-home">
    <section className="pd-hero">
      <div className="pd-hero-copy"><span className="pd-eyebrow">RECOVER / SECURE / GOVERN</span><h1>Critical IT Shouldn’t Become a <em>Business Risk.</em></h1><p>PatuhData helps Indonesian and international businesses protect critical systems, recover from disruption, strengthen cybersecurity, and maintain compliance readiness.</p><div className="pd-hero-actions"><ArchitectLink /><a className="pd-button pd-button-outline" href="#solutions">View Our Solutions <span aria-hidden="true">↓</span></a></div><p className="pd-hero-topics">Cloud <span>•</span> Cybersecurity <span>•</span> Business Continuity <span>•</span> PDP &amp; Compliance</p></div>
      <div className="pd-architecture" aria-label="Recover, Secure, and Govern support your critical business systems"><div className="pd-diagram-title"><span>BUILT AROUND YOUR BUSINESS</span><span aria-hidden="true">↗</span></div><div className="pd-system"><span className="pd-system-icon" aria-hidden="true">▦</span><h2>Critical business systems</h2><p>Secure. Recoverable.<br />Ready for compliance.</p></div><div className="pd-diagram-branches" aria-hidden="true"/><div className="pd-diagram-pillars">{coreSolutions.map(s => <a href={`/solutions/${s.slug}`} key={s.slug}><small>{s.number}</small><strong>{s.label}</strong><span>{s.slug === 'recover' ? 'Keep business moving' : s.slug === 'secure' ? 'Reduce technology risk' : 'Build readiness'}</span></a>)}</div><p className="pd-diagram-note">Architecture → Implementation → Ongoing operations</p></div>
    </section>
    <section className="pd-section pd-problems"><div className="pd-heading"><span className="pd-eyebrow">THE RISKS BEHIND THE TECHNOLOGY</span><h2>When technology fails,<br />the business pays the price.</h2></div><div className="pd-four-grid">{[
      ['Downtime & Data Loss', 'Backups exist, but nobody knows whether recovery will actually work.'],
      ['Cybersecurity Risk', 'Endpoints, networks, cloud environments, and access controls are increasingly difficult to manage.'],
      ['Compliance Pressure', 'Customers, banks, auditors, and regulators continuously request evidence.'],
      ['Limited Internal IT Capacity', 'Growing businesses need senior technical capability without building a large specialist team.'],
    ].map(([title, text], index) => <article className="pd-problem" key={title}><span className="pd-number">0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="pd-section pd-solutions" id="solutions"><div className="pd-heading"><span className="pd-eyebrow">THREE SOLUTIONS. ONE BUSINESS PRIORITY.</span><h2>Recover. Secure. Govern.</h2><p>{positioning}</p></div><div className="pd-three-grid">{coreSolutions.map(s => <article className="pd-solution" key={s.slug}><div className="pd-solution-top"><span>{s.number}</span><span aria-hidden="true">{s.slug === 'recover' ? '↻' : s.slug === 'secure' ? '◇' : '≡'}</span></div><h3>{s.name}</h3><h4>{s.title}</h4><p>{s.description}</p><ul>{s.services.map(item => <li key={item}>{item}</li>)}</ul><a className="pd-card-link" href={`/solutions/${s.slug}`}>{s.cta}<Arrow /></a></article>)}</div></section>
    <DeliveryProcess />
    <section className="pd-section pd-industries" id="industries"><div className="pd-heading"><span className="pd-eyebrow">WHO WE SERVE</span><h2>For businesses where<br />technology risk matters.</h2></div><div className="pd-two-grid">{industries.map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="pd-section pd-indonesia" id="indonesia"><div><span className="pd-eyebrow">GLOBAL CONTROLS. LOCAL READINESS.</span><h2>Entering the<br />Indonesian Market?</h2><p>PatuhData helps international technology companies translate their existing global security and privacy controls into the evidence, governance, and technical readiness expected by Indonesian enterprise customers.</p><ArchitectLink interest={indonesiaInterest} label="Indonesia Technology Readiness" /></div><div className="pd-readiness"><p className="pd-readiness-label">BUILD ON WHAT YOU ALREADY HAVE</p><ul><li>Existing ISO 27001?<span aria-hidden="true">✓</span></li><li>Existing global DPO?<span aria-hidden="true">✓</span></li><li>Existing security architecture?<span aria-hidden="true">✓</span></li></ul><h3>Great. We don’t ask you to start again.</h3><p>PatuhData identifies the Indonesian gaps and helps close them.</p></div></section>
    <section className="pd-section pd-managed" id="managed-services"><div className="pd-heading"><span className="pd-eyebrow">ONGOING OPERATIONAL OWNERSHIP</span><h2>Don’t just implement it.<br />Keep it working.</h2></div><div className="pd-three-grid">{coreSolutions.map(s => <article key={s.slug}><h3>{s.managed}</h3><ul>{s.tasks.map(task => <li key={task}>{task}</li>)}</ul><a className="pd-card-link" href={inquiryHref(s.managed)}>Discuss {s.managed.toLowerCase()}<Arrow /></a></article>)}</div><p className="pd-service-note">Monthly managed services available based on environment and business criticality. Coverage, response times, and responsibilities are agreed during scoping.</p></section>
    <section className="pd-section pd-ecosystem"><div className="pd-heading"><span className="pd-eyebrow">TECHNOLOGY ECOSYSTEM</span><h2>We design solutions using<br />proven enterprise technology.</h2><p>Architecture and product selection follow your requirements and existing environment.</p></div><ul className="pd-vendors">{technologyLogos.map(({ name, src }) => <li key={name}><img src={src} alt={name} loading="lazy" decoding="async" width="132" height="52" /><span aria-hidden="true">{name}</span></li>)}</ul></section>
    <section className="pd-section pd-about" id="about"><div className="pd-heading"><span className="pd-eyebrow">WHY PATUHDATA</span><h2>Business risk first.<br />Practical systems next.</h2></div><div className="pd-two-grid">{differentiators.map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="pd-section pd-founder"><div className="pd-founder-name"><span className="pd-eyebrow">MEET THE FOUNDER</span><h2>Richard Rusli</h2><p>Founder &amp; Solutions Architect</p></div><div className="pd-founder-copy"><h3>From complex requirements<br />to systems that work.</h3><p>Richard’s background spans software engineering, cloud infrastructure, APIs, eKYC, and technology product delivery. He founded PatuhData to help businesses translate technology and compliance challenges into practical systems that can be implemented and operated.</p><ArchitectLink /></div></section>
    <section className="pd-section" id="resources"><div className="pd-heading"><span className="pd-eyebrow">RESOURCES</span><h2>Better questions.<br />Better technology decisions.</h2><p>Practical guides for leaders responsible for resilience, security, and readiness.</p></div><ResourceCards /><div className="pd-existing-resources"><span>More from PatuhData</span><a href="/insights/managed-it">Why growing businesses need a managed service provider ↗</a><a href="/insights/uu-pdp-data-residency">UU PDP and data residency in Indonesia ↗</a></div></section>
    <FinalCTA />
  </main>
}
export function CoreSolutionPage({ solution }: { solution: CoreSolution }) {
  return <main className="pd-home"><section className="pd-solution-hero"><a href="/#solutions" className="pd-back">← All solutions</a><span className="pd-eyebrow">{solution.title}</span><h1>{solution.name}</h1><p>{solution.description}</p><ArchitectLink interest={solution.interest} label={solution.cta} /></section><section className="pd-section pd-solution-scope"><div className="pd-heading"><span className="pd-eyebrow">WHAT WE DO</span><h2>{solution.outcome}</h2></div><ul className="pd-scope-list">{solution.services.map(item => <li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul></section><section className="pd-section pd-deliverables"><div className="pd-heading"><span className="pd-eyebrow">FROM PLAN TO PRACTICE</span><h2>What we build together</h2><p>Scope and deliverables are agreed after understanding your environment.</p></div><div className="pd-two-grid">{solution.deliverables.map((item, i) => <article key={item}><span className="pd-number">0{i + 1}</span><p>{item}</p></article>)}</div>{solution.slug === 'govern' && <p className="pd-service-note">Readiness support helps you prepare and operate controls. Certification and regulatory decisions remain with the relevant independent bodies.</p>}</section><DeliveryProcess /><section className="pd-section pd-managed-summary"><div><span className="pd-eyebrow">KEEP IT WORKING</span><h2>{solution.managed}</h2><p>{solution.tasks.join(' · ')}</p><p>Monthly managed services scoped around your environment and business criticality.</p></div><ArchitectLink interest={solution.managed} /></section><FinalCTA /></main>
}
