import WhatsAppButton from './WhatsAppButton'
import type { Language } from '../data/recoveryCopy'
import { pdpInsightPaths, pdpLawSource, pdpRecoveryInsight } from '../data/pdpRecoveryInsight'
import CookieConsent from './CookieConsent'

export default function PdpRecoveryArticle({ lang }: { lang: Language }) {
  const c = pdpRecoveryInsight[lang]
  const home = lang === 'id' ? '/' : '/en'
  return <div className="rl-site"><header className="rl-header"><a href={home} aria-label="PatuhData"><img src="/logo.png" alt="PatuhData" width="160" height="48" /></a><a className="rl-text-link" href={`${home}#resources`}>{c.back}</a><div className="rl-language"><a href={pdpInsightPaths.id} hrefLang="id" lang="id" aria-current={lang === 'id' ? 'page' : undefined}>ID</a><span>/</span><a href={pdpInsightPaths.en} hrefLang="en" lang="en" aria-current={lang === 'en' ? 'page' : undefined}>EN</a></div></header><main className="rl-wrap rl-insight-page"><article><header><p className="rl-eyebrow">{c.category}</p><h1>{c.title}</h1><p className="rl-lead">{c.summary}</p><p className="rl-article-date">PatuhData · <time dateTime="2026-09-28">{c.date}</time></p></header><p className="rl-article-intro">{c.intro}</p>{c.sections.map(section => <section key={section.title}><h2>{section.title}</h2><p>{section.text}</p>{'source' in section && <a className="rl-article-source" href={pdpLawSource}>{section.source}</a>}</section>)}<section><h2>{c.checklistTitle}</h2><ol>{c.checklist.map(item => <li key={item}>{item}</li>)}</ol><p>{c.conclusion}</p></section><aside className="rl-article-note"><p>{c.note}</p><a href={pdpLawSource}>{c.sourceLabel}</a><p>{c.sourceNote}</p></aside><section><h2>{c.related}</h2><ul><li><a href="/resources/can-you-restore-your-backup">{lang === 'id' ? 'Menguji pemulihan backup (English)' : 'Testing whether your backup can be restored'}</a></li><li><a href="/insights/uu-pdp-data-residency">{lang === 'id' ? 'UU PDP dan lokasi data (English)' : 'UU PDP and data residency'}</a></li></ul><a className="rl-button" href={`${home}#contact`}>{c.cta} ↗</a></section></article></main><footer className="rl-footer"><div className="rl-wrap"><div className="rl-footer-bottom"><p>© 2026 PT PatuhData Solusi Nusantara</p><div className="rl-footer-legal"><a href={`${home}#resources`}>Insights & Blog</a><a href="/privacy">Privacy Policy</a><a href="/terms">Terms</a><button type="button" onClick={() => window.dispatchEvent(new Event('patuhdata:open-consent'))}>{lang === 'id' ? 'Pengaturan Cookie' : 'Cookie Settings'}</button></div></div></div></footer><CookieConsent lang={lang} /><WhatsAppButton lang={lang} /></div>
}
