import { resilienceServices } from '../data/resilienceServices'

const Arrow = () => <span aria-hidden="true">↗</span>

export default function ResilienceHome() {
  return <main id="main-content" className="cr-home">
    <section className="cr-hero" aria-labelledby="hero-title">
      <div className="cr-hero-copy"><p className="cr-eyebrow">UU PDP · OPERATIONAL PRIVACY</p><h1 id="hero-title">Turn privacy obligations<br /><span>into everyday practice.</span></h1><p className="cr-lead">Assess readiness, establish your privacy operating model, maintain RoPA and DPIA evidence, and remediate the technology gaps behind your UU PDP program.</p><div className="cr-actions"><a className="cr-button" href="/contact?service=uu-pdp-readiness-assessment">Start With an Assessment <Arrow /></a><a className="cr-link" href="#services">Explore the program <span aria-hidden="true">↓</span></a></div><p className="cr-hero-note">ASSESS <span>/</span> IMPLEMENT <span>/</span> MAINTAIN <span>/</span> REMEDIATE</p></div>
      <figure className="cr-photo"><img src="/modern-office-space-interior.jpg" alt="Modern professional office workspace" width="1920" height="1280" loading="eager" /><figcaption>Privacy compliance built around real processes, accountable owners, and usable evidence.</figcaption></figure>
    </section>

    <nav className="cr-section-nav" aria-label="On this page"><span>A practical UU PDP program</span><a href="#services">Services</a><a href="#approach">How it works</a><a href="#evidence">What you receive</a><a href="#boundaries">Our role</a></nav>

    <section className="cr-section cr-intro" id="about"><div><p className="cr-eyebrow">BEYOND DOCUMENTS</p><h2>Compliance should work<br />when the audit ends.</h2></div><div><p>Policies alone do not show how personal data moves through your organization, who owns each decision, or whether important controls operate consistently.</p><p>PatuhData connects privacy governance with implementation. We help your team document processing, assess higher-risk activities, maintain evidence, and address validated technical gaps through a focused operating model.</p><a className="cr-link" href="/contact?service=uu-pdp-readiness-assessment">Discuss your current position <Arrow /></a></div></section>

    <section className="cr-section cr-services" id="services"><div className="cr-heading"><div><p className="cr-eyebrow">ONE CONNECTED PROGRAM</p><h2>Start with clarity.<br />Build what you need.</h2></div><p>Four defined engagements that can stand alone or form one continuous privacy-improvement program.</p></div><div className="cr-service-grid">{resilienceServices.map(s => <article key={s.slug}><div className="cr-service-top"><span>{s.n}</span><span aria-hidden="true">{s.icon}</span></div><h3>{s.title}</h3><p>{s.text}</p><ul>{s.bullets.slice(0, 3).map(b => <li key={b}>{b}</li>)}</ul><a className="cr-link" href={`/services/${s.slug}`} aria-label={`Explore ${s.title}`}>View engagement <Arrow /></a></article>)}</div></section>

    <section className="cr-section cr-approach" id="approach"><div className="cr-heading"><div><p className="cr-eyebrow">DELIVERY MODEL</p><h2>Focused enough to finish.<br />Structured enough to maintain.</h2></div><p>Each stage has a defined objective, agreed inputs, named owners, and documented outputs.</p></div><ol className="cr-steps">{[['Discover', 'Understand the organization, processing activities, systems, stakeholders, and existing evidence.'], ['Prioritize', 'Evaluate gaps and privacy risks, then agree what should be addressed first.'], ['Implement', 'Establish the records, workflows, controls, and responsibilities included in scope.'], ['Maintain', 'Review evidence, track change, and remediate validated operational or technical gaps.']].map(([title, description], i) => <li key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{description}</p></li>)}</ol></section>

    <section className="cr-section cr-evidence" id="evidence"><div><p className="cr-eyebrow">TANGIBLE OUTPUTS</p><h2>Evidence your team<br />can actually use.</h2><p>Deliverables are confirmed in writing before work begins and tailored to the agreed scope, systems, and maturity of your organization.</p><a className="cr-link" href="/contact">Request a scoped conversation <Arrow /></a></div><div className="cr-deliverables">{[['Current-state findings', 'A grounded view of observed practices, gaps, dependencies, and limitations.'], ['RoPA and risk records', 'Structured records of processing activities, data flows, risks, decisions, and owners.'], ['Operational workflows', 'Usable procedures for DPIAs, requests, incidents, reviews, and evidence maintenance.'], ['Remediation plan', 'Prioritized governance and technology improvements with accountable next actions.']].map(([title, description], i) => <article key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>

    <section className="cr-ecosystem" id="boundaries"><div><p className="cr-eyebrow">TRUST THROUGH CLARITY</p><h2>Operational expertise,<br />with clear boundaries.</h2><p>PatuhData provides privacy-program implementation and technology remediation. We do not promise certification or guaranteed compliance outcomes.</p></div><div className="cr-scope-note"><strong>Legal questions stay with qualified counsel</strong><p>Our work supports implementation and evidence. Where formal legal interpretation or representation is required, we coordinate with or defer to appropriately qualified legal professionals.</p></div></section>

    <section className="cr-section cr-consult" id="contact"><div><p className="cr-eyebrow">A PRACTICAL FIRST STEP</p><h2>Start with what is<br />happening today.</h2></div><div><p>Tell us how your organization uses personal data, what has already been prepared, and where you need clarity. We’ll recommend a focused starting scope.</p><a className="cr-button" href="/contact?service=uu-pdp-readiness-assessment">Start With an Assessment <Arrow /></a></div></section>
  </main>
}
