import type { Metadata } from 'next'
import { PageHero } from '@/components/PageHero';import { SectionIntro } from '@/components/SectionIntro';import { ServiceList } from '@/components/ServiceList';import { FinalCta } from '@/components/FinalCta';import { meta,site } from '@/data/site'
export const metadata:Metadata={...meta.dpo,openGraph:{title:meta.dpo.title,description:meta.dpo.description,url:'/managed-dpo'}}
const duties=['Advise management on Indonesian personal-data obligations','Monitor privacy governance and processing activities','Review product, vendor and data-transfer risks','Maintain a privacy advisory and action register','Conduct DPIA screening','Support data-subject request handling','Provide initial guidance during personal-data incidents','Report material privacy risks to management','Liaise with relevant stakeholders within the agreed scope']
const receives=['One named external DPO','Appointment and reporting framework','Initial processing inventory','Privacy baseline and action register','Product and vendor privacy reviews within agreed limits','Data-subject request guidance','Personal-data incident guidance','Monthly governance meeting','Monthly activity and risk report','Quarterly management briefing']
const platform=['Borrower and loan information','Collection notes and call recordings','Collector access and bulk exports','Automated case prioritisation','Retention and deletion','Collection agencies and technology providers','Overseas support access','Borrower request and incident workflows']
const boundaries=['ISO certification','Guaranteed regulatory compliance','24/7 cybersecurity operations','Forensic investigation','Software development','Unlimited policy or contract drafting','Formal legal opinions','Full DPIAs unless specifically included','Additional personnel beyond the named DPO']
const roles=[['DPO','Advise, monitor, review, document and escalate'],['Client management','Approve decisions, allocate resources and accept risks'],['Product and engineering','Implement product and technical controls'],['Security team','Detect, contain and investigate security incidents'],['Legal counsel','Provide formal legal opinions and represent the company where required'],['PatuhData','Manage the commercial engagement and service governance']]
export default function Dpo(){return <main id="main"><PageHero eyebrow="Primary service" title="Managed DPO as a Service" lead="Independent privacy advice, monitoring and management reporting for organisations operating in Indonesia." cta="Discuss Your DPO Requirement"><p>PatuhData arranges one named external privacy professional to perform the agreed DPO function. The DPO advises management, monitors personal-data processing, supports privacy-risk assessments and escalates material issues while the client remains responsible for decisions and implementation.</p></PageHero><section className="section shell"><SectionIntro eyebrow="DPO mandate" title="What your DPO will do" text={`Practitioner profile: ${site.dpoProfile}`}/><ServiceList items={duties}/></section><section className="section shell"><SectionIntro eyebrow="Defined deliverables" title="What you receive"/><ServiceList items={receives}/></section><section className="dark-section"><div className="section shell"><SectionIntro light eyebrow="Worked example" title="Collection platform oversight" text="For a loan-collection platform, the DPO may review the processing environment across product, operations and vendors."/><ServiceList items={platform}/><div className="output-panel" style={{marginTop:24}}><h3>Possible outputs</h3><p>Personal-data flow · Processing inventory entry · Controller-processor assessment · DPIA screening · Risk and remediation register · Management report</p></div></div></section><section className="section shell"><SectionIntro eyebrow="Accountability" title="Responsibilities remain explicit"/><table className="responsibility-table"><tbody>{roles.map(r=><tr key={r[0]}><th>{r[0]}</th><td>{r[1]}</td></tr>)}</tbody></table><div className="statement">The DPO provides independent advice and monitoring. The client remains accountable for its processing decisions, operational controls and implementation of recommendations.</div></section><section className="section shell"><SectionIntro eyebrow="Service boundaries" title="What Managed DPO does not include" text="Additional work may be separately scoped where appropriate."/><div className="boundary-list">{boundaries.map(x=><span key={x}>{x}</span>)}</div></section><FinalCta title="Discuss your DPO requirement." secondary/></main>}
